# Generated by Django 5.2.8 on 2026-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryexpense',
            name='designation',
            field=models.CharField(default='Staff', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryexpense',
            name='salary_type',
            field=models.CharField(choices=[('daily_wage', 'Daily Wage'), ('monthly', 'Monthly')], default='daily_wage', max_length=20),
        ),
    ]
